#!/usr/bin/env bash
# Installing nginx web server.

# The colors
blue='\e[1;34m'
brown='\e[0;33m'
green='\e[1;32m'
reset='\033[0m'

echo -e "${blue}Updating and installing ${brown}Nginx${blue}.${reset}\n"
sudo apt-get update -y -qq && \
	 sudo apt-get install nginx -y

echo -e "\n${blue}Setting up some minor stuff.${reset}\n"

# startes nginx service
sudo service nginx start

# allowes nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Giving user ownership to website files
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backing up default index.
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Creates new index
echo -e "Hello World!" > /var/www/html/index.nginx-debian.html

# Settes /redirect_me to youtube video
sudo sed -i '24i\	rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Restarting the nginx
sudo service nginx restart

echo -e "\n${green}Completed.${reset} ✅\n"

