#!/usr/bin/env bash
# extending previous exercise cmd and displays bash word, this allows to get the PID of your Bash process
# cannot use pgrep
# shellcheck disable=SC2009

./1-list_your_processes | grep "bash"
