#!/usr/bin/env bash
# fixing nginx server that dont shut off via daemon manager.
mv /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
cp /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default 
service nginx start