#!/usr/bin/env bash
# The script is:
#  Creating a file /var/run/myscript.pid contain script PID.
#  Display "To infinity and beyond" indefinitely.
#  Display "I hate the kill command" while receiving SIGTERM.
#  Display "Y U no love me?!" upon receiving SIGINT.
#  Delet the file /var/run/myscript.pid, terminate upon
#+  receiving SIGQUIT or SIGTERM

terminator() {
  rm /var/run/myscript.pid
  exit
}

echo "$$" > /var/run/myscript.pid

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "Y U no love me?!"' SIGINT
  trap 'echo "I hate the kill command" && terminator' SIGTERM
  trap 'terminator' SIGQUIT
done
