#!/usr/bin/env bash
# display "Best School" 10 times.

count=0
while [ $count -lt 11 ]
do
    if [ $count = 9 ]
    then
        echo "Hi"
    else
        echo "Best School"
    fi
    let count+=1
done
