#!/usr/bin/env bash
# displaying Loops from 1 to 10:
# "bad luck" 4th iteration.
# "good luck" 8th iteration.
# "Best School" for all other iterations.

i=0

while [ $i -lt 10 ]
do
  if [ $i -eq 3 ]
  then
    echo "bad luck"
  elif [ $i -eq 7 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  (( i++ ))
done

